version: "3.9"
services:
  server:
    image: nginx:mainline-alpine
    ports:
      - 8080:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - .:/usr/share/nginx/html/
    depends_on:
      - php-fpm
    links:
      - php-fpm
  php-fpm:
    image: joseluisq/php-fpm:8.2
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=128M"
      - "PHP_FPM_LISTEN=9090"
      - "PHP_SESSION_GC_MAXLIFETIME=1440"
      - "PHP_EXPOSE_PHP=Off"
    expose:
      - "9090"
    volumes:
      - .:/usr/share/nginx/html/
