version: "3.9"
services:
  server:
    image: nginx:mainline-alpine
    ports:
      - 8080:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - .:/usr/share/nginx/html/
    depends_on:
      - php-fpm
    links:
      - php-fpm
    networks:
      net6:
        ipv6_address: fd97:3e0c:cbdc::10
    dns: fd97:3e0c:cbdc::1
  php-fpm:
    image: joseluisq/php-fpm:8.2
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=128M"
      - "PHP_FPM_LISTEN=9090"
      - "PHP_SESSION_GC_MAXLIFETIME=1440"
      - "PHP_EXPOSE_PHP=Off"
    expose:
      - "9090"
    volumes:
      - .:/usr/share/nginx/html/
    networks:
      net6:
        ipv6_address: fd97:3e0c:cbdc::20
    dns: fd97:3e0c:cbdc::1
networks:
  net6:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd97:3e0c:cbdc::/64
          gateway: fd97:3e0c:cbdc::1
